import jsPDF from "jspdf";

export function downloadJobMatchReport(result) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  let y = 20;

  // Header
  doc.setFillColor(249, 115, 22);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);

  doc.text("HireLens AI", 20, 18);

  doc.setFontSize(12);

  doc.text("AI Job Match Report", 20, 28);

  y = 48;

  doc.setTextColor(80);
  doc.setFontSize(11);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    y
  );

  y += 15;

  doc.setFillColor(59, 130, 246);

  doc.roundedRect(20, y, 170, 20, 3, 3, "F");

  doc.setTextColor(255);

  doc.setFont("helvetica", "bold");

  doc.text("Job Match Score", 25, y + 12);

  doc.text(
    `${result.match_score}%`,
    175,
    y + 12,
    { align: "right" }
  );

  y += 30;

  function addSection(title, content) {
    if (y > pageHeight - 40) {
      doc.addPage();
      y = 20;
    }

    doc.setTextColor(37, 99, 235);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);

    doc.text(title, 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(60);
    doc.setFontSize(11);

    if (Array.isArray(content)) {
      content.forEach((item) => {
        const lines = doc.splitTextToSize(`• ${item}`, 165);

        doc.text(lines, 25, y);

        y += lines.length * 6;
      });
    } else {
      const lines = doc.splitTextToSize(content, 170);

      doc.text(lines, 20, y);

      y += lines.length * 6;
    }

    y += 8;
  }

  addSection(
    "Matching Skills",
    result.matching_skills || []
  );

  addSection(
    "Missing Skills",
    result.missing_skills || []
  );

  addSection(
    "Missing Keywords",
    result.missing_keywords || []
  );

  addSection(
    "Recruiter Feedback",
    result.recruiter_feedback || ""
  );

  addSection(
    "Improvement Suggestions",
    result.improvement_suggestions || []
  );

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    "Generated by HireLens AI • Created by Praveen Seeri",
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  doc.save("HireLens_AI_Job_Match_Report.pdf");
}