import jsPDF from "jspdf";

export function downloadResumeReport(review) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  let y = 20;

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("HireLens AI", 20, 18);

  doc.setFontSize(12);
  doc.text("AI Resume Analysis Report", 20, 28);

  y = 48;

  doc.setTextColor(80);
  doc.setFontSize(11);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    y
  );

  y += 15;

  function scoreBox(title, value, color) {
    doc.setFillColor(...color);

    doc.roundedRect(20, y, 170, 18, 3, 3, "F");

    doc.setTextColor(255);

    doc.setFont("helvetica", "bold");

    doc.text(title, 25, y + 11);

    doc.text(String(value), 175, y + 11, {
      align: "right",
    });

    y += 25;
  }

  scoreBox(
    "Resume Score",
    `${review.resume_score}/100`,
    [37, 99, 235]
  );

  scoreBox(
    "ATS Score",
    `${review.ats_score}/100`,
    [22, 163, 74]
  );

  scoreBox(
    "Recruiter Confidence",
    `${review.recruiter_confidence}%`,
    [147, 51, 234]
  );

  function addSection(title, content) {
    if (y > pageHeight - 40) {
      doc.addPage();
      y = 20;
    }

    doc.setTextColor(37, 99, 235);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(title, 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(60);
    doc.setFontSize(11);

    if (Array.isArray(content)) {
      content.forEach((item) => {
        const lines = doc.splitTextToSize(`• ${item}`, 165);

        doc.text(lines, 25, y);

        y += lines.length * 6;
      });
    } else {
      const lines = doc.splitTextToSize(content, 170);

      doc.text(lines, 20, y);

      y += lines.length * 6;
    }

    y += 8;
  }

  addSection("First Impression", review.first_impression);
  addSection("Overall Assessment", review.assessment);
  addSection("Strengths", review.strengths);
  addSection("Weaknesses", review.weaknesses);
  addSection("Missing Skills", review.missing_skills);
  addSection("ATS Observations", review.ats_observations);
  addSection("Top Improvements", review.top_improvements);

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by HireLens AI • Created by Praveen Seeri",
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  doc.save("HireLens_AI_Report.pdf");
}